name: Actualizar M3U Multi-Canal
on:
  repository_dispatch:
    types: [update_link]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Crear archivo M3U
        run: |
          echo "${{ github.event.client_payload.link }}" > lista_fresca.m3u
      - name: Guardar cambios
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add lista_fresca.m3u
          git commit -m "Lista actualizada desde Panel Web"
          git push
