name: Actualizar Lista
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4 # Versión actualizada

      - name: Configurar Python
        uses: actions/setup-python@v5 # Versión actualizada
        with:
          python-version: '3.11'

      - name: Instalar Librerias
        run: pip install -r requirements.txt

      - name: Ejecutar Script
        run: python actualizador.py

      - name: Guardar Cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lista_fresca.m3u
          git commit -m "Lista actualizada automaticamente" || exit 0
          git push
