name: Actualizar Lista
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4 # Versión actual

      - name: Configurar Python
        uses: actions/setup-python@v5 # Versión actual
        with:
          python-version: '3.11'

      - name: Instalar Librerias
        run: pip install requests # Instalación directa más rápida

      - name: Ejecutar Script
        run: python actualizador.py

      - name: Guardar Cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add lista_fresca.m3u
          git commit -m "Lista actualizada" || exit 0
          git push
